name: C/C++ CI

on: [push]

jobs:
  build:
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: make test
  #     run: make test

    runs-on: macOS-latest

    #env:
    #  HOMEBREW_NO_AUTO_UPDATE: 1
    
    steps:
    - uses: actions/checkout@v1

    - name: install redis
      run: brew install redis

    - name: start redis server
      run: brew services start redis

    - name: make test
      run: make test
